import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Support Ticket Demo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex bg-white`}>
        <Nav />
        <div className='w-full'>
          <h1 className='text-5xl font-semibold text-gray-700 pt-8 px-8'>Support Ticket</h1>
          {children}
        </div>
      </body>
    </html>
  );
}
